name: Update README

on:
  # Run on all pushes (even PR branches)
  push:
  # Manual button in Github
  workflow_dispatch:
  # On a schedule
  schedule:
    - cron: '30 * * * *'

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Check-out repo
        uses: actions/checkout@v2

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Python dependencies
        run: |
          make install

      - name: Update README.md
        run: |
          make -B README.md

      - name: Commit and push if README.md changed
        run: |
          git config --global user.email "readme-bot@example.com"
          git config --global user.name "README-bot"
          git diff --quiet || (git add README.md && git commit -m "Update README")
          git push
